# Generated by Django 2.2.1 on 2019-05-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
