# Generated by Django 2.2.1 on 2019-05-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='image',
            field=models.ImageField(default=0, upload_to='', verbose_name='/imgs'),
            preserve_default=False,
        ),
    ]
