# Generated by Django 2.2.1 on 2019-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_point_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
