# Generated by Django 2.2.1 on 2019-05-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20190512_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='source',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
